quarkus.http.port=8181

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ${QUARKUS_DATASOURCE_USERNAME:user}
quarkus.datasource.password = ${QUARKUS_DATASOURCE_PASSWORD:12345}
quarkus.datasource.jdbc.url = jdbc:postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5434}/agencia_validation

quarkus.kafka.devservices.enabled = true
producer.kafka.host = ${QUARKUS_KAFKA_HOST:localhost}:${QUARKUS_KAFKA_PORT:9092}